# Generated by Django 2.1.4 on 2019-01-26 16:46

from django.db import migrations, models
import django.db.models.deletion
import my_shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, default='my_shop/default_phone.png', upload_to=my_shop.models.image_folder, verbose_name='Иконка товара')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('count', models.IntegerField(db_index=True, verbose_name='Количество товаров')),
                ('operation_system', models.CharField(db_index=True, max_length=100, verbose_name='ОС')),
                ('slug_o_p', models.SlugField(blank=True, max_length=100)),
                ('ram', models.IntegerField(db_index=True, verbose_name='ОЗУ')),
                ('battery', models.IntegerField(db_index=True, verbose_name='Объем батареи')),
                ('price', models.FloatField(db_index=True, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, default='0000000', on_delete=django.db.models.deletion.CASCADE, to='my_shop.Category')),
            ],
            options={
                'verbose_name': 'Мобильный телефон',
                'verbose_name_plural': 'Мобильные телефоны',
                'ordering': ['name'],
            },
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together={('id', 'name', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='mobilephone',
            index_together={('id', 'name', 'slug')},
        ),
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('count', models.IntegerField(db_index=True, verbose_name='Количество товаров')),
                ('bright', models.IntegerField(db_index=True, verbose_name='Яркость')),
                ('price', models.FloatField(db_index=True, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, default='0000000', on_delete=django.db.models.deletion.CASCADE, to='my_shop.Category')),
                ('icon', models.ImageField(blank=True, default='my_shop/phone_icons/default_phone.png', upload_to=my_shop.models.image_folder, verbose_name='Иконка товара')),
            ],
            options={
                'verbose_name': 'Проектор',
                'verbose_name_plural': 'Проекторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug_name', models.SlugField(blank=True, max_length=100)),
                ('count', models.IntegerField(db_index=True, verbose_name='Количество товаров')),
                ('diagonal', models.FloatField(db_index=True, verbose_name='Диагональ')),
                ('screen', models.CharField(db_index=True, max_length=100, verbose_name='Разрешение')),
                ('slug_screen', models.SlugField(blank=True, max_length=100)),
                ('price', models.FloatField(db_index=True, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, default='0000000', on_delete=django.db.models.deletion.CASCADE, to='my_shop.Category')),
            ],
            options={
                'verbose_name': 'Телевизор',
                'verbose_name_plural': 'Телевизоры',
                'ordering': ['name'],
            },
        ),
        migrations.AlterIndexTogether(
            name='tv',
            index_together={('id', 'name', 'slug_name')},
        ),
        migrations.AlterIndexTogether(
            name='projector',
            index_together={('id', 'name', 'slug')},
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='slug_name',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='tv',
            name='icon',
            field=models.ImageField(blank=True, default='my_shop/phone_icons/default_phone.png', upload_to=my_shop.models.image_folder, verbose_name='Иконка товара'),
        ),
        migrations.AlterIndexTogether(
            name='tv',
            index_together={('id', 'name', 'slug')},
        ),
    ]
